### PR TITLE
upgrades runtime to node 20

### LINKED ISSUE #31: update node version
github shows warning when running actions:
```txt
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: pozetroninc/github-action-get-latest-release@master
```

### PR DESCRIPTION
**Pull request by baywet**
fixes #31

CC @neil-pozetroninc

### CODE REVIEW

**Review by ftasbasi — APPROVED** [review]
LGTM

**Comment by baywet** [comment]
@neil-pozetroninc gentle reminder, can we get a review/merge/tag from you on this one please?

**Comment by neil-pozetroninc** [comment]
@baywet I did some gardening with help from your dependabot PR.

That should cover what was previously covered by this PR. Let me know if I missed anything, otherwise I think we can close this PR now?

**Comment by baywet** [comment]
confirmed! thanks for merging the other one. closing

**Pull request closed without merging**
