### PR TITLE
feat: add optional auth token, fix deprecations and build with ncc

### LINKED ISSUE #11: Release description
Hi, 

We are using your action to check if one of our dependencies has a new release, and if it does we open a PR that updates our dependency. One thing that we are missing that we would love to have is the release description so that we can add it to our PR, would you be ok if I created a PR to add the `description` of the release in the outputs?

Thanks

### LINKED ISSUE #20: error: Not found
Hello 

I am trying to use this, but I am getting an error "Not Found".

I am using it like this:
- name: Get Last Release Id
      id: latest-release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: ${{ github.repository }}
        excludes: prerelease, draft

The repo in question has at least two releases created (manually). So I am not sure what is not able to find.

Thanks

### LINKED ISSUE #23: Node.js 12 actions are deprecated
Very useful action. 
Thanks for having it!
We are getting an error in our CI.
`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: pozetroninc/github-action-get-latest-release`

Could you please update [action.yml](https://github.com/pozetroninc/github-action-get-latest-release/blob/master/action.yaml) to use Node 16?

`runs: using: 'node16'`

### LINKED ISSUE #24: How to pass GitHub API token
In my GitHub Action run [here](https://github.com/netheril96/securefs/actions/runs/3562145096/jobs/5983618839), I have an error `Error: API rate limit exceeded for 207.254.3.33. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)` Is there any way to pass a GitHub API token via environment variable?

### LINKED ISSUE #25: Use of deprecated `set-output` command in `@actions/core`
According to [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), `set-output` has been deprecated and `@actions/core` should be updated to at least `v1.10.0` to use the new behaviour.

Would it be possible to upgrade? It looks like this action might otherwise stop working at the end of May 2023.

### PR DESCRIPTION
**Pull request by shawaj**
feat: add optional auth token, fix deprecations and build with ncc

- add optional auth token
- bump to node16
- bump action/core to 1.10.0
- bump dependencies to latest versions
- remove node_modules folder and package with ncc build
- update readme to add new features and update older actions in examples
- update package.json version
- add more info to package.json
- bump package-lock.json
- add linter and fix linting errors
- bump version number to 0.7.0 to follow tags on this repo
- auto-build with ncc using github actions and push updated index.js to repo if available

Closes: #25 
Closes: #24 
Closes: #23 
Closes: #11 
Closes: #20
Closes: #26 

Co-authored-by: @dp1 <dp1@users.noreply.github.com> (looked at #26 and wanted to give credit as well!)

### CODE REVIEW

**Comment by shawaj** [comment]
@neil-pozetroninc @pozetroninc let me know if this looks ok to you or if you would like any updates?

Currently, it will build an index.js for ncc every time you push (if there have been updates that would change this)

I did think about possibly only doing this if the version tag in package.json was updated....and adding an automated tag and release action to the workflow as well so that when you bump the version number in the package.json file on master, it builds automatically, tags the commit and creates a new release. 

It would still require manual intervention to publish the release to the marketplace but this would be simply editing the release and ticking the box.

However, perhaps this is overkill and releases are just as easily done manually

**Comment by trevorphillipscoding** [comment]
awesome pr. hopefully we can get it pushed through. just started using this and instantly saw the deprecation issue.

**Comment by shawaj** [comment]
@trevorphillipscoding if you want you can use the updated action straight away from the forked version. I'm doing that on another repo here:

https://github.com/NebraLtd/hm-gatewayrs/blob/d1016d7f01a2dfdfa94f9699b20fe23dfb6dc246/.github/workflows/check-latest-release.yml#L19-L23

It's not on the marketplace that version but you can use as long as you use the different name and `@patch-1` branch :-)

And then super easy to change back once it's merged 👌

**Comment by devzwf** [comment]
Fantastic PR who seems to fix many issue....
hopefully this repo is still maintained ? or time for a fork ?

**Comment by shawaj** [comment]
> Fantastic PR who seems to fix many issue.... hopefully this repo is still maintained ? or time for a fork ?

You can already use my fork as described in the message above if it doesn't get merged for a bit

**Comment by neil-pozetroninc** [comment]
Woah. I haven't had a chance to look at this repo for a while. Thank you @shawaj!

I'll take a look now, if it all works like it says on the tin I'll merge this ASAP

**Review by neil-pozetroninc — APPROVED** [review]

**Comment by shawaj** [comment]
> Woah. I haven't had a chance to look at this repo for a while. Thank you @shawaj!
> 
> I'll take a look now, if it all works like it says on the tin I'll merge this ASAP

No problem @neil-pozetroninc - thanks for creating a really useful action 😊

**Pull request merged**
